import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {type: 'autogenerated', dirName: '.'},
  ],
  productTrainingSidebar: [
    'product-training/intro',
    {
      type: 'category',
      label: 'Core Products',
      items: [
    'product-training/laptops-desktops',
    'product-training/servers',
    'product-training/networking',
      ],
    },
    {
      type: 'category',
      label: 'Components',
      items: [
        'product-training/cards',
        'product-training/drives',
        'product-training/gpu',
        'product-training/memory',
        'product-training/processors',
        'product-training/storage',
      ],
    },
    {
      type: 'category',
      label: 'Mobile Devices',
      items: [
        'product-training/phones',
        'product-training/tablets',
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
